version: '3'
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - '5173:5173'
        networks:
            - app-network

    admin:
        build:
            context: .
            dockerfile: Dockerfile.admin
        ports:
            - '5174:5174'
        networks:
            - app-network

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - '8080:8080'
        networks:
            - app-network
        environment:
            - JUDGER_URL=http://judger:8090
            - DATABASE_URL=mongodb://mongo:27017/FloatPoint
        depends_on:
            - mongo
    judger:
        build:
            context: .
            dockerfile: Dockerfile.judger
        ports:
            - '8090:8090'
        networks:
            - app-network

    mongo:
        image: mongo:6.0
        container_name: mongo
        networks:
            - app-network
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
