services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASS:-postgres}
            POSTGRES_DB: ${DB_NAME:-postgres}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

    minio:
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
        ports:
            - "9000:9000"
            - "9001:9001"
        command: >
            server /data --console-address ":9001"
        volumes:
            - miniodata:/data
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq
        networks:
            - app-network

    judger:
        build:
            context: .
            dockerfile: Dockerfile.judger
        networks:
            - app-network
        privileged: true
        env_file:
            - judger/.env
        environment:
            JUDGER_ID: ${JUDGER_ID:-1}
            MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio}
            DB_HOST: ${DB_HOST:-postgres}
            RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}

    server:
        build:
            context: .
            dockerfile: Dockerfile.server
        networks:
            - app-network
        environment:
            MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio}
            DB_HOST: ${DB_HOST:-postgres}
            RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
        env_file:
            - server/.env
        ports:
            - "4000:4000"

networks:
    app-network:
        driver: bridge

volumes:
    pgdata:
    miniodata:
    rabbitmqdata:
